# Este arquivo requer a extensão REST Client para funcionar corretamente.

### requisição POST para criar produto
POST http://localhost:3000/products
content-type: application/json

{
    "barcode": "1234567899",
    "name": "Guaravita",
    "orderReferenceDays": 30
}

### requisição GET para buscar todos os produtos
GET http://localhost:3000/products
content-type: application/json

### requisição GET para buscar produto
GET http://localhost:3000/products/1234567899
content-type: application/json

### requisição POST para criar pedido do produto
POST http://localhost:3000/product-orders
content-type: application/json

{
    "barcode": "1234567890",
    "quantity": 100,
    "orderDate": "2026-02-20T00:00:00.000Z"
}

### requisição POST para criar entrada do produto
POST http://localhost:3000/product-inputs
content-type: application/json

{
    "productOrderId": "696a29bc-ea0f-4cf2-993e-9676a3062efd",
    "quantity": 120,
    "inputDate": "2026-02-28T00:00:00.000Z"
}

### requisição POST para criar saída do produto
POST http://localhost:3000/product-outputs
content-type: application/json

{
    "barcode": "1234567890",
    "quantity": 2,
    "outputDate": "2026-02-28T00:00:00.000Z"
}

### requisição DELETE para deletar entrada do produto
DELETE http://localhost:3000/product-inputs/aafdd4cc-726a-440c-b531-b97ad0384b79

### requisição DELETE para deletar saída do produto
DELETE http://localhost:3000/product-outputs/012b7e13-26f4-432e-a00a-d03178fbd31b