# Este arquivo requer a extensão REST Client para funcionar corretamente.

### requisição POST para criar produto
POST http://localhost:3000/products
content-type: application/json

{
    "barcode": "1234567890",
    "name": "Coca Cola",
    "orderReferenceDays": 30
}

### requisição GET para buscar todos os produtos
GET http://localhost:3000/products
content-type: application/json

### requisição GET para buscar produto
GET http://localhost:3000/products/1234567899
content-type: application/json

### requisição POST para criar pedido do produto
POST http://localhost:3000/product-orders
content-type: application/json

{
    "barcode": "1234567899",
    "quantity": 100,
    "orderDate": "2026-02-20T00:00:00.000Z"
}

### requisição POST para criar entrada do produto
POST http://localhost:3000/product-inputs
content-type: application/json

{
    "productOrderId": "50e48cfa-d3c4-4025-bbcc-16b6ad8217bb",
    "quantity": 120,
    "inputDate": "2026-02-28T00:00:00.000Z"
}

### requisição POST para criar saída do produto
POST http://localhost:3000/product-outputs
content-type: application/json

{
    "barcode": "1234567899",
    "quantity": 1,
    "outputDate": "2026-02-28T00:00:00.000Z"
}

### requisição DELETE para deletar entrada do produto
DELETE http://localhost:3000/product-inputs/d1e679ff-bb29-4321-b71c-caead882403a

### requisição DELETE para deletar saída do produto
DELETE http://localhost:3000/product-outputs/1683e042-5f9b-497f-ab65-d2a79e2176bd