# Este arquivo requer a extensão REST Client para funcionar corretamente.

### requisição POST para criar produto
POST http://localhost:3000/products
content-type: application/json

{
    "barcode": "1234567899",
    "name": "Guaravita",
    "orderReferenceDays": 30
}

### requisição GET para buscar todos os produtos
GET http://localhost:3000/products
content-type: application/json

### requisição GET para buscar produto
GET http://localhost:3000/products/1234567899
content-type: application/json

### requisição POST para criar pedido do produto
POST http://localhost:3000/product-orders
content-type: application/json

{
    "barcode": "1234567899",
    "quantity": 100,
    "orderDate": "2026-02-20T00:00:00.000Z"
}

### requisição POST para criar entrada do produto
POST http://localhost:3000/product-inputs
content-type: application/json

{
    "productOrderId": "fbe5078f-93df-40d8-b533-acb455f94018",
    "quantity": 120,
    "inputDate": "2026-02-28T00:00:00.000Z"
}

### requisição POST para criar saída do produto
POST http://localhost:3000/product-outputs
content-type: application/json

{
    "barcode": "1234567899",
    "quantity": 2,
    "outputDate": "2026-02-28T00:00:00.000Z"
}

### requisição DELETE para deletar entrada do produto
DELETE http://localhost:3000/product-inputs/9831e1c3-2077-427b-8bc8-7dd0d7d106d4

### requisição DELETE para deletar saída do produto
DELETE http://localhost:3000/product-outputs/7a3fa9d7-ba87-40ca-8eac-22c388ff5e99